### ISSUE TITLE
ゲームシステム(ルール等)

### ISSUE THREAD

**Issue by f-aogiri** [Woocs/WaterChallenge#5]
展示に向く(客の回転が良く楽しい)をやって

**Comment by zakiko** [comment]
最低でも3回ぐらいは撃てる程度の時間制限にします
Ａｎｄｒｏｉｄで銃の方向を調整し、発射します(Ａｎｄｒｏｉｄには十字ボタンと発射ボタンがある)
的に当たれば1点とし、ユーザーは制限時間内に多く稼ぐことを目指します
ディスプレイ(ノートＰＣ)には、最高得点が表示されます。これは2日間合わせてでよいでしょう。

また、縦方向角度調整、横方向角度調整、発射は同時にできないようにします
これでどうでしょうか？よければcloseしてください

**Comment by zakiko** [comment]
Wikiに書くべき内容っぽい

**Comment by f-aogiri** [comment]
これでいいと思うのでCloseします。
Wiki更新しました。

**Comment by zakiko** [comment]
お疲れ様です
